package com.nexus.nexwell;

import com.codename1.components.FloatingActionButton;
import com.codename1.components.MultiButton;
import static com.codename1.ui.CN.*;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import static com.codename1.ui.Component.CENTER;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;
import com.nexus.nexwell.games.*;

import com.nexus.nexwell.forms.HomePageForm;
import static com.codename1.ui.util.Resources.getGlobalResources;
import com.nexus.nexwell.homepage.UIController;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class NexWell{
    
    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }

        UIController.showSplashScreen();
        
    }
    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

      
    

    
  
    

}



        /*
        Form hi = new Form("Hi World", BoxLayout.y());
        
        Button helloButton = new Button("Hello World", getGlobalResources().getImage(WEST));
        hi.add(helloButton);
        Label logo = new Label("What the fuck am I doing?");
        
        
        FloatingActionButton fab = FloatingActionButton.createFAB(FontImage.MATERIAL_ADD);
        fab.bindFabToContainer(hi);
        fab.addActionListener(e -> addNewItem());
        
        helloButton.addActionListener(e -> hello());
        hi.getToolbar().addMaterialCommandToSideMenu("Hello Command",
        FontImage.MATERIAL_CHECK, 4, e -> hello());
        hi.getToolbar().addMaterialCommandToSideMenu("Profile", FontImage.MATERIAL_ACCOUNT_CIRCLE, 3, e-> hello());
        hi.getToolbar().addMaterialCommandToSideMenu("Settings", FontImage.MATERIAL_SETTINGS, 3, e-> hello());
        hi.getToolbar().addMaterialCommandToSideMenu("Bookings", FontImage.MATERIAL_CALENDAR_MONTH, 3, e-> hello());
        hi.getToolbar().addMaterialCommandToSideMenu("Mindfulness", FontImage.MATERIAL_COFFEE, 3, e-> hello());
        
        hi.show();
        
        new HomePageForm().show();
        */